### ISSUE TITLE
Galpy orbit initialization

### ISSUE THREAD

**Issue by nstarman** [ilikecubesnstuff/commensurability#35]
I'm seeing:
`galpyWarning: Orbit's initialization normalization ro and zo are incompatible with SkyCoord's galcen_distance (should have galcen_distance^2 = ro^2 + zo^2)`

ro and zo can be passed to galpy's constructors / methods, and I guess pidgey should manage that. It can cause issues when doing frame transforms from galpy.

— https://github.com/openjournals/joss-reviews/issues/7009

**Comment by ilikecubesnstuff** [comment]
Currently `ro` and `zo` *are* passed in within `pidgey` using `galpy.util.conversion.get_physical`. When I try to address this warning in `pidgey`, I get this error if I change the inputs for orbit initialization:
```
AssertionError: Physical conversion for the Orbit object is not consistent with that of the Potential given to it
```

Is there a way to specify the input such that this assertion error isn't thrown AND the warning is not thrown either?

**Comment by nstarman** [comment]
Hard to address without seeing the stack trace.
SkyCoord has the galactocentric frame on it, so you can get the relevant parameters from it. And galpy's r0, v0 are arbitary, just used for unit conversions, so these should be able to be set based on the frame. But yes, it must be given consistently across all of galpy.

**Comment by ilikecubesnstuff** [comment]
I don't know how to tackle this issue. The current fix in `pidgey` is to use `galpy.util.conversion.get_physical`:
```
        pot_units = self.conversion.get_physical(pot)
        orbit = self.orbit.Orbit(skycoord, **pot_units)
```
But this creates the warnings you mentioned above. I am using the script `examples/using_galpy/rotating_bar.py` to test this, and here is what I have tried:

In this case, the `skycoord` frame has the following properties: `(ra, dec) in deg (266.4051, -28.936175)>, galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg)`

If I pass `zo` as anything other than 20.8 pc, I get the following traceback:
```
Traceback (most recent call last):
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/examples/using_galpy/rotating_bar.py", line 49, in <module>
    tanal = TessellationAnalysis(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/src/commensurability/analysis.py", line 387, in __init__
    self._construct_image_with_mp(pidgey_chunksize, mp_chunksize, progressbar)
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/src/commensurability/analysis.py", line 405, in _construct_image_with_mp
    orbits = self.backend.compute_orbit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/pidgey/src/pidgey/base.py", line 94, in compute_orbit
    self._result = self._compute_orbit(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/pidgey/src/pidgey/galpy_backend.py", line 33, in _compute_orbit
    orbit = self.orbit.Orbit(
            ^^^^^^^^^^^^^^^^^
  File "/home/subhadeep/miniconda3/envs/c14y_galpy/lib/python3.12/site-packages/galpy/orbit/Orbits.py", line 357, in __init__
    self._setup_parse_coordtransform(vxvv, ro, vo, zo, solarmotion, radec, lb)
  File "/home/subhadeep/miniconda3/envs/c14y_galpy/lib/python3.12/site-packages/galpy/orbit/Orbits.py", line 479, in _setup_parse_coordtransform
    raise ValueError(
ValueError: Orbit initialization's zo different from SkyCoord's z_sun; these should be the same for consistency
```

If I pass `ro` as anything other than 8.0 kpc OR `vo` as anything other than 220.0 km / s, I get the following traceback:
```
galpyWarning: Orbit's initialization normalization ro and zo are incompatible with SkyCoord's galcen_distance (should have galcen_distance^2 = ro^2 + zo^2)
Traceback (most recent call last):
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/examples/using_galpy/rotating_bar.py", line 49, in <module>
    tanal = TessellationAnalysis(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/src/commensurability/analysis.py", line 387, in __init__
    self._construct_image_with_mp(pidgey_chunksize, mp_chunksize, progressbar)
  File "/mnt/c/Users/User/Documents/GitHub/commensurability/src/commensurability/analysis.py", line 405, in _construct_image_with_mp
    orbits = self.backend.compute_orbit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/pidgey/src/pidgey/base.py", line 94, in compute_orbit
    self._result = self._compute_orbit(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/User/Documents/GitHub/pidgey/src/pidgey/galpy_backend.py", line 43, in _compute_orbit
    orbit.integrate(t, pot, **integration_kwargs)
  File "/home/subhadeep/miniconda3/envs/c14y_galpy/lib/python3.12/site-packages/galpy/orbit/Orbits.py", line 1394, in integrate
    _check_consistent_units(self, pot)
  File "/home/subhadeep/miniconda3/envs/c14y_galpy/lib/python3.12/site-packages/galpy/orbit/Orbits.py", line 8094, in _check_consistent_units
    assert physical_compatible(
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: Physical conversion for the Orbit object is not consistent with that of the Potential given to it
```

**Comment by nstarman** [comment]
I think you can define a galactocentric frame from the galpy and then transform the SkyCoord to that frame. Then pass it to galpy.

**Comment by ilikecubesnstuff** [comment]
That does appear to produce the same warning. I am doing the following within `pidgey/galpy_backend.py`:
```py
        pot_units = self.conversion.get_physical(pot)
        skycoord_galcen = skycoord.transform_to(coord.Galactocentric())
        orbit = self.orbit.Orbit(skycoord_galcen, **pot_units)
```
Entering specific arguments into `coord.Galactocentric` appears to have no effect.

**Comment by nstarman** [comment]
Maybe time to call in the real expert on all things galpy — @jobovy

**Comment by jobovy** [comment]
I'm happy to help debug this issue, I have a lot of experience with similar issues 😄 .... The issue might be that ``skycoord_galcen = skycoord.transform_to(coord.Galactocentric())`` sets the ``galcen_distance``, ``z_sun`` etc. attributes of the ``SkyCoord`` and the defaults can be incompatible with ``galpy``'s. But it would be helpful to have some additional info:
* What version of ``galpy`` are you using? (asking because I made some recent changes to how SkyCoord frame parameters are treated, see jobovy/galpy#715
* Could you create a self-contained example that leads to the issue? For example, if the code in https://github.com/ilikecubesnstuff/commensurability/issues/35#issuecomment-2730896578 is the issue, perhaps make a version of that code that starts from the potential used and the ``coord`` object?

**Comment by ilikecubesnstuff** [comment]
Hi @jobovy! Thank you so much for offering to help debug this :)

I was on galpy version `1.10.1`, but I just upgraded to `1.10.2` and the warning still persists.
The follow code produces the warning in my environment with galpy `1.10.2`:
```py
import astropy.coordinates as c
import astropy.units as u
import galpy.orbit as go
import galpy.potential as gp
from galpy.util import conversion

# potential
omega = 30 * u.km / u.s / u.kpc
halo = gp.NFWPotential(conc=10, mvir=1)
disc = gp.MiyamotoNagaiPotential(amp=5e10 * u.solMass, a=3 * u.kpc, b=0.1 * u.kpc)
bar = gp.SoftenedNeedleBarPotential(
    amp=1e9 * u.solMass, a=1.5 * u.kpc, b=0 * u.kpc, c=0.5 * u.kpc, omegab=omega
)
pot = [halo, disc, bar]

# initial condition
ic = c.SkyCoord(
    x=8 * u.kpc,
    y=0 * u.kpc,
    z=1 * u.kpc,
    v_x=0 * u.km / u.s,
    v_y=220 * u.km / u.s,
    v_z=0 * u.km / u.s,
    frame="galactocentric",
    representation_type="cartesian",
)

# lines adapted from pidgey
pot_units = conversion.get_physical(pot)
ic = ic.transform_to(c.Galactocentric())  # warning appears with and without this line
orbit = go.Orbit(ic, **pot_units)
```

**Comment by jobovy** [comment]
Great, thanks! Okay, so the issue is that when you initialize a ``SkyCoord`` in Galactocentric coordinates, ``astropy`` sets its default frame parameters, which are currently ``galcen_distance = 8.122 kpc`` and ``z_sun = 20.8 pc`` (and also the Solar velocity). When you set up the potential without specifying ``ro`` and ``vo``, ``galpy``'s defaults are used, which have ``ro=8 kpc`` (and ``vo=220 km/s``). So these are then incompatible (compatibility would be that ``galcen_distance^2 = ro^2 + zo^2``).

I'm not sure how ``pidgey`` does things, but here are some ways to deal with this:
1. Ignore the ``SkyCoord``'s frame parameters. I _think_ that's what is currently done and what leads to the warning, but better would be to just set the relevant ``SkyCoord`` frame parameters to the value that is compatible with ``galpy``'s. E.g., ``ic.galcen_distance = sqrt(ro**2.+zo**2.)``, where you first get ``ro`` from running ``conversion.get_physical(pot)`` as you do above. Note that you should be able to set ``ic.z_sun`` to whatever you want as long as you (i) don't explicitly set ``zo`` in the Orbit initialization and (ii) make sure ``galcen_distance`` is compatible with ``(ro,z_sun)``. 
2. _First_ set up the SkyCoord, then extract its ``galcen_distance`` and set ``ro`` based on the assumed ``z_sun`` to ``ro = sqrt(galcen_distance**2.-z_sun**2.)``. And then use that ``ro`` when setting up the potential.
3. _First_ set up the potential, extract ``ro``, and use it to set up the SkyCoord. So roughly as follows:
   ```python
   rovo = conversion.get_physical(pot)
   ro=rovo["ro"]
   vo =rovo["vo"]
   # initial condition
   z_sun = 0.0208*u.kpc
   ic = c.SkyCoord(
       x=8 * u.kpc,
       y=0 * u.kpc,
       z=1 * u.kpc,
       v_x=0 * u.km / u.s,
       v_y=220 * u.km / u.s,
       v_z=0 * u.km / u.s,
       frame="galactocentric",
       representation_type="cartesian",
       galcen_distance=numpy.sqrt(ro**2.*u.kpc**2 + z_sun**2),
       z_sun=z_sun
   )
   ```
   That gets rid of the warning.

Note that there isn't an issue with the assumed solar velocity, because ``astropy`` sets the solar velocity directly, while ``galpy`` splits it into circular velocity + ``solarmotion`` and if you don't explicitly set ``solarmotion``, then they are just made consistent for any ``vo``.

Ideally, at some point ``galpy`` would not use ``ro,vo`` for both unit conversion and the Solar <-> Galactocentric frame conversion, but there is no plan to change this currently.

**Comment by ilikecubesnstuff** [comment]
Thank you so much! For `pidgey`, I think the best option is defining a new `SkyCoord` object based on the one passed in, just with the extra keyword arguments for consistency in `galpy`. (`commensurability` defines the potential and initial conditions separately and then passes both in.)

**Comment by ilikecubesnstuff** [comment]
Changes addressing this issue are now merged in `pidgey` and `commensurability`.
