### ISSUE TITLE
Missing package warnings are cryptic

### ISSUE THREAD

**Issue by michael-petersen** [ilikecubesnstuff/commensurability#4]
When testing `examples/using_galpy/phase_slice.py` on a new python version, got the following error:
```
(base) mpetersen@MPAir using_galpy % python3.11 phase_slice.py 
with chunksize=5: 100%|███████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.54it/s]
Traceback (most recent call last):
  File "/Users/mpetersen/Code/commensurability/examples/using_galpy/phase_slice.py", line 34, in <module>
    canal.save_image(f'mw_bar_{SIZE}.hdf5')
  File "/opt/homebrew/lib/python3.11/site-packages/commensurability/analysis/analysis.py", line 153, in save_image
    file = FileIO(filename)
           ^^^^^^^^^^^^^^^^
TypeError: _unavailable.<locals>.Unavailable.__init__() takes 1 positional argument but 2 were given
```

The cause was simply that I hadn't installed `h5py` yet, which was fairly straightforward to figure out, but I think this is not necessarily clear from the error message. Something to be fixed?

Although I suspect the easier fix could be to add `h5py` as a dependency.

**Comment by michael-petersen** [comment]
I think this is solved with new packaging.
